Support Legends
piever/SplitApplyPlot.jl pull request #32
Opened 2021-04-25 12:16 UTC by greimel

```julia
tbl1 = (x = rand(100), y = rand(100), z = 20 .* rand(100), grp1 = rand(["a", "b"], 100), grp2 = rand(["c", "d"], 100))

cols = mapping(:x => "The X", :y => "The Y");
grp = mapping(marker = :grp1 => nonnumeric => "Group", color = :grp2 => "Other", markersize = :z);
scat = visual(Scatter)
aog = data(tbl1) * cols * scat * grp

fig = aog |> draw
Legend(fig.figure[1,2], aog)
fig
```

<img width="563" alt="image" src="https://user-images.githubusercontent.com/6280307/115992955-9cf4c680-a5d0-11eb-9c60-c29df937b17f.png">

2021-04-25 13:47 UTC, piever commented
Thanks a lot, this looks pretty nice already!

I think there is no need to have the legend drawn automatically in `draw` (it'd be easy to add that later in any case), but it would help to have an example of drawing the legend in the Example Gallery (could probably be the same as the one you're showing above, plus one with a colorbar).

Btw, a couple of practical things to add docs to gallery.jl:
- to try things locally, you need to be on the master branch of documenter (otherwise, it does not handle many svgs in one page well)
- it's probably better to rebase this branch (conflict-free) before adding docs, because I've just modified the whole doc setup

2021-04-27 09:11 UTC, greimel commented
It turned out that I need to do some adjustments for the more general setup here.

I've not pushed this yet, but locally this works

![image](https://user-images.githubusercontent.com/6280307/116216273-bd479100-a748-11eb-8697-0b9cb1211e5e.png)

That is, you can mix and match `PlotType`s and continous/categorical scales now and use a variable more than once.

2021-04-30 08:08 UTC, greimel commented
## What needs to be fixed future PRs

- [ ] correctly handle composite plot types (now fall back to `poly`)
- [ ] specifying the order of legend elements (should be poly then line then marker)
- [ ] correctly handle the case when no plottype is given in `visual` (currently this errors)

## A few examples

![image](https://user-images.githubusercontent.com/6280307/116582257-76f35d00-a915-11eb-8d26-f4ab8d497302.png)

![image](https://user-images.githubusercontent.com/6280307/116666195-fa0ac680-a99a-11eb-8eb2-5bf4c47f4902.png)

![image](https://user-images.githubusercontent.com/6280307/116666258-0b53d300-a99b-11eb-8bf9-595be9095b8e.png)

![image](https://user-images.githubusercontent.com/6280307/116666350-245c8400-a99b-11eb-827e-e708f982e45e.png)

2021-04-30 10:24 UTC, piever requested changes

2021-04-30 10:38 UTC, piever commented
Thanks for adding the consolidation bit. I've left some comments. Other than some formatting nitpicking, I think the main point is to have a clean structure for `SubLegend` and `SubLegendEntry` that allows for merging. My suggestion is something along the lines of

```julia
struct SubLegendEntry
    label::String
    visuals::Vector{Visual} # each plottype has its one attributes
end

struct SubLegend
    title::String
    entries::Vector{SubLegendEntry}
end
```

We should make sure that this allow for a `merge!` method on sublegends that combines entries in the correct way.

Then, consolidation becomes much easier using dicts (well, an `OrderedCollections.LittleDict` to remember the order). For example:

```julia
sublegend_dict = LittleDict{String, SubLegend}()
for sublegend in sublegends
    key = sublegend.title
    current = get!(sublegend_dict, key, Sublegend(key, SubLegendEntry[]))
    merge!(current, sublegend)
end
```

2021-04-30 10:39 UTC, piever commented on src/guides/legend.jl
> +function _legend(P, attribute, scale::ContinuousScale, title)
(Thinking more carefully, scratch the above type hierarchy, I try to explain my idea more clearly in https://github.com/piever/SplitApplyPlot.jl/pull/32#issuecomment-830005943.)

2021-04-30 11:59 UTC, greimel commented
Hi, I'll probably take a few days do address all this. I wanted to push a working version before the weekend.

2021-05-06 11:26 UTC, piever commented
@greimel , just a heads up that I'm about to do some `Entries / AxisEntries` rework, so that some details of how things are done (in particular legend consolidations) will likely need to change. I was thinking to merge this as is (even if a bit preliminar) and adjust it as I do the refactor. (Otherwise you'd have to work on things that may likely need to change in the near future...)

Do you have some local changes you'd like to push or can I go ahead and merge this version?

2021-05-06 14:53 UTC, greimel commented
hi @piever, sorry that this has stalled a bit. I've not worked on this in the meantime, I was busier than I thought with other things.

Despite the messy state it should be fine to merge. If necessary I will help cleaning this up later.

2021-05-06 14:55 UTC, greimel commented
also feel free to commit the suggested changes.

2021-05-06 19:01 UTC, merged